.PHONY: all
all:
	cat ../../sorbusdomestica.geojson | ./make-maps-images.mjs ../../maps/tiles ../../maps/node

local:
	cat ~/git/speierling-site/data/sorbusdomestica.geojson | ./make-maps-images.mjs ~/sorbusdomestica/tiles/tiles ~/sorbusdomestica/tiles/node
